[package]
name = "your_package_name"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="simple_publisher"
path="src/simple_publisher.rs"
[[bin]]
name="simple_subscriber"
path="src/simple_subscriber.rs"
[dependencies]
rclrs = "*"
std_msgs = "*"
